### ISSUE TITLE
Can't load it on Paper 1.15.2 (Build 205)

### ISSUE THREAD

**Issue by stanislasbdx** [Megamezzomixer/Taser#1]
When I load it via Plugman or with a natural server reload, it says that the plugin isn't "up to date", I have the last version :x
On my spigot server it works, but now on my paper one...
![image](https://user-images.githubusercontent.com/17954501/84062729-1935e980-a9c0-11ea-9c7d-046f5b87a8ce.png)

**Comment by Megamezzomixer** [comment]
Thanks for the Issue. I'm currently on it.

**Comment by Megamezzomixer** [comment]
Your Stack Trace refers me to https://github.com/Megamezzomixer/Taser/blob/22dc89f96f992266def6a83647cf3c73a8cc082e/src/de/megamezzomixer/Taser/Main.java#L40

Basically Papercraft cannot use the internal Bukkit logger as it seems. Currently trying another method.
