### ISSUE TITLE
cannot load the plugin 

### ISSUE THREAD

**Issue by GEROGIANNIS** [Megamezzomixer/Taser#9]
it says this 
[11:31:56] [Server thread/ERROR]: Could not load 'plugins\Taser (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: de/megamezzomixer/Taser/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error.txt](https://github.com/Megamezzomixer/Taser/files/6330793/error.txt)

what ive to do to fix this?
open the file i attached to see the error

**Comment by Megamezzomixer** [comment]
Which java version do you use?

**Comment by GEROGIANNIS** [comment]
1 sec let me check

**Comment by Megamezzomixer** [comment]
That is because you use an older java version than I compiled the plugin with.
The plugin is compiled in Java 11.10.0.19

**Comment by GEROGIANNIS** [comment]
ok so i will update my java and if it gats fixed ill close the issue

**Comment by Megamezzomixer** [comment]
Okay, let me know, please.

**Comment by GEROGIANNIS** [comment]
btw it says ive java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Comment by Megamezzomixer** [comment]
Yes, you still use Java 8.
I have built it with OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
Which is Java 11.

**Comment by GEROGIANNIS** [comment]
ok everything fixed thank you for the fast response  (let me just check if i can get the taser on the game)

**Comment by GEROGIANNIS** [comment]
ok it works now ty
